// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvylszybrcoqhaauyesk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eWxzenlicmNvcWhhYXV5ZXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDk2ODIsImV4cCI6MjA3MjMyNTY4Mn0.HSQ5BmYzFjI10q7SoTD7uXuxBM1_T-sMCsO9kN1aMds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});